services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: book_db
    ports:
      - "5433:5432"
    networks:
      - lms-network

  lms-book-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-book-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/book_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - lms-network


networks:
  lms-network:
    driver: bridge
