spring:
  application:
    name: lms-book-app
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: iapurba30
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
